server:
  port: 8889
logging:
  level:
    io.github.guoshiqiufeng.loki: debug
    io.github.guoshiqiufeng.lokitest: debug

spring:
  kafka:
    consumer:
      auto:
        offset:
          reset: earliest
      auto-commit-interval: 1000
      enable-auto-commit: true

loki:
  global-config:
    mq-config:
      mq-type: kafka
      address: 127.0.0.1:9092