server:
  port: 8889
logging:
  level:
    io.github.guoshiqiufeng.loki: debug
    io.github.guoshiqiufeng.lokitest: debug

spring:
  profiles:
    active: single
#loki:
#  redis:
#    support-type: spring_data
