server:
  port: 8889
logging:
  level:
    io.github.guoshiqiufeng.loki: debug
    io.github.guoshiqiufeng.lokitest: debug

loki:
  global-config:
    mq-config:
      mq-type: redis
      address: 127.0.0.1:6379
      auth: true
      password: 123456