server:
  port: 8889
logging:
  level:
    io.github.guoshiqiufeng.loki: debug
    io.github.guoshiqiufeng.lokitest: debug

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 12

loki:
  global-config:
    mq-config:
      mq-type: redis
      address: 127.0.0.1:6379
      auth: true
      password: 123456
#      mq-type: ROCKET_MQ
#      address: 127.0.0.1:8081
#      auth: false
#      username: username
#      password: password
#      connect-timeout: 300
#      max-attempts: 5
